JIRA ID :PD-669
cloudlending/Solutions-Configurations pull request #17
Opened 2022-07-01 07:35 UTC by npaulq2ebankingCK

DESCRIPTION :Pr for BAO data
Test : NO
Comments : NO

2022-07-07 10:02 UTC, jitendra30 approved these changes

2022-07-07 13:59 UTC, nirajsinhaCLS requested changes

2022-07-07 13:59 UTC, nirajsinhaCLS commented on BAO/Configurations/genesis__Policy_Condition_Category_Association__c/Article_of_Organization_PolicyArticles_of_Organization.json
> +     "genesis__External_Id__c": "Article_of_Organization_PolicyArticles_of_Organization",
Duplicate names are appended.

2022-07-07 13:59 UTC, nirajsinhaCLS commented on BAO/Configurations/genesis__Policy_Condition_Category_Association__c/Article_of_Organization_PolicyArticles_of_Organization.json
> +     "genesis__External_Id__c": "Article_of_Organization_PolicyArticles_of_Organization",
Add underscore between two names.

2022-07-07 13:59 UTC, nirajsinhaCLS commented on BAO/Configurations/genesis__Policy_Condition_Category_Association__c/Article_of_Organization_PolicyArticles_of_Organization.json
> +     "genesis__External_Id__c": "Article_of_Organization_PolicyArticles_of_Organization",
Please do for all Policy_Condition_Category_Association records.

2022-07-07 13:59 UTC, nirajsinhaCLS commented on BAO/Configurations/genesis__Policy_Exception_Definition__c/PED_0000009.json
> +     "genesis__External_ID__c": "PED_0000009",
Use genesis__Policy_Condition_Name__c field for the external id.

2022-07-11 10:18 UTC, nirajsinhaCLS requested changes

2022-07-11 10:18 UTC, nirajsinhaCLS commented on BAO/Configurations/genesis__Policy_Exception_Definition__c/PED_0000009.json
> +     "genesis__External_ID__c": "PED_0000009",
Please update this.

2022-07-11 11:22 UTC, jitendra30 approved these changes

2022-07-11 11:25 UTC, nirajsinhaCLS approved these changes

2022-07-11 11:29 UTC, YashasGCCLS approved these changes

2022-07-11 11:30 UTC, merged